### ISSUE TITLE
definition of `isConsonant`

### ISSUE THREAD

**Issue by marcosh** [Mikolaj/minimorph#1]
Currently `isConsonant` returns true for every character which is not a vowel, including numbers and symbols.

Possibly a more correct definition would be just

```haskell
isConsonant :: Char -> Bool
isConsonant = (`elem` "bcdfghjklmnpqrstvwxyz") . toLower
```

**Comment by Mikolaj** [comment]
Yes, that definitely sounds saner. Have you tried if tests pass with this definition? 

However, I wonder what's the convention for words that contain numbers, e.g., user identifiers Sandra2004 or U2 or the silly abbreviations like 4u (admittedly, it's not English any more)? Are the numbers treated as consonants rather than vowels? Or do all grammatical/lexical rules mention numbers explicitly and separately? It probably doesn't matter for the uses inside the library, but the function is exported, so it may matter for somebody. We, effectively, create a third category of letters and all definitions now have to take the category into account (worth mentioning in comments somewhere).

**Comment by marcosh** [comment]
the tests all pass

not being a native English speaker, it's hard for me to say... I guess that for grammar rules, one considers the word format of a number/symbol (I mean, `two` for `2`)

I opened a PR. Feel free to ditch if you deem it not appropriate

**Comment by Mikolaj** [comment]
Oh, you are probably right, one just spells out the numbers. So, to handle them, we'd need to check how they are spelled and then, say, consider the first letter or the last. Unfortunately, for the last letter, the spelling depends on the grammatical form of the number, so it can't be done on the lexical level alone. So, we could only make kludges for the easiest cases. But to attempt that, we need to remove numbers from the consonant class. Let me nit-pick your PR and then I'd happily accept it.
